- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
> [#4] 프로젝트 폴더 재생성

- README.md
- 리드미 템플릿만 첨부했습니다
- 프로젝트가 완성되면 추가해보아요 :) 
>
> [#0] 리드미 업데이트

- README.md
- 리드미 안의 이미지를 업데이트 했습니다(임시)
- 언제든 변경가능! 
> 수정 편하게 가능해요 :) 
> 리드미 관련이라 애매하여.. PR 숫자는 0번으로 생성했습니다
> [#0] 리드미 이미지 업데이트

- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
- FiveGuyes/FiveGuyes/Sources/Models/ImageAnimation.swift
- FiveGuyes/FiveGuyes/Sources/Stores/FeedProgressTimer.swift
- FiveGuyes/FiveGuyes/Sources/Views/Components/FeedPagingRectangle.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/AnimatedImageView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/FeedView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/ImageSlideView.swift
- FeedView를 추가했습니다.
- Feed의 이미지 인덱스와 progress bar를 관리하기 위해 async stream을 사용한 타이머를 구현했습니다.
- 현재 유저가 직접 스크롤할 때 progress bar가 업데이트되지 않습니다. 유저가 스크롤할 때 currentFeedIndex를 변경해야 하는데, 아직 적절한 방법을 찾지 못했습니다. 좋은 해결책이 있다면 공유 부탁드립니다.
- 변수 명명에 신경을 썼지만, 타이머가 FeedView에 의존하지 않도록 분리하고 싶었으나 현재는 의존적인 형태로 작성되었습니다. 이를 개선할 수 있는 방법에 대한 의견이 있으시면 말씀해주시면 감사하겠습니다.
> [#14] Feed view 구현

- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
- FiveGuyes/FiveGuyes/Sources/Models/BookModel.swift
- FiveGuyes/FiveGuyes/Sources/Models/ReadingScheduleCalculator.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/Testing/ReadingTestView.swift
- 책과 관련한 데이터 저장을 위한 모델 추가
- 책 페이지 계산 모델 추가
-
> [#45} 책 페이지 계산 모델 추가

- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
- FiveGuyes/FiveGuyes/Info.plist
- FiveGuyes/FiveGuyes/Sources/Models/BookDetails.swift
- FiveGuyes/FiveGuyes/Sources/Models/UserBook.swift
- FiveGuyes/FiveGuyes/Sources/Views/Components/CompletionListView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookProgress/DailyProgressView.swift
- swiftData 모델에서 에러가 계속해서 발생하여 relationship 관계를 삭제합니다.
- 완독 리스트를 지우는 로직을 우선 보류합니다.
-
> [#50] model에서 relationship 관계 삭제

- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
- FiveGuyes/FiveGuyes/Sources/Views/Components/WeeklyPageCalendarView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Components/WeeklyReadingProgressView.swift
- 할당량을 읽지 않은 날은 컬러를 통해 구분해줍니다.
- 뒷 배경에 쉐도우가 보이는 버그를 수정합니다.
-
> [#59] weekly calendar 업데이트

- FiveGuyes/FiveGuyes/Sources/Models/NotificationType.swift
-노티를 보내는 시간을 11시, 23시에서 9시, 21시로 변경합니다.
-
> [#65] Change noti time

- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookSetting/CompletionCalendarView.swift
- 과거 날짜는 달력에서 선택되지 않게 합니다.
- 과거 날짜의 UI를 수정합니다.
-
> [#67] 캘린더 뷰에서 과거 날짜 선택 막기

- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
- FiveGuyes/FiveGuyes/Sources/Views/Components/WeeklyReadingProgressView.swift
- FiveGuyes/FiveGuyes/Sources/Views/EmptyNotiView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookCompletion/CompletionCelebrationView.swift
- 이미지 에셋의 이름을 업데이트해줍니다.
- 참조값만 남아 있던 파일을 삭제해줍니다.
-
> [#74] image asset명 업데이트

- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookSetting/CompletionCalendarView.swift
- 도서 설정 화면의 캘린더 뷰에서 오늘 날짜를 디폴트로 시작 날짜로 보여줍니다.
-
> [#76] 기간 선정 화면에서 투데이 표시

- FiveGuyes/FiveGuyes/Sources/Views/Screen/Main/MainHomeView.swift
- 메인 홈 스크롤 뷰에서 백그라운드 컬러를 그라데이션으로 교체합니다
-
> [#82] 메인 홈 백그라운드 컬러 변경

- FiveGuyes/FiveGuyes.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookSetting/FinishGoalView.swift
- 패딩값을 조절해 15pro 기준으로 하루 할당량 쪽수가 화면 내에서 잘리는 현상을 해결했습니다. 
> [#85] 텍스트 한 줄 잘림 해결

- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
- FiveGuyes/FiveGuyes/Resources/Extensions/Calendar+Extension.swift
- FiveGuyes/FiveGuyes/Resources/Extensions/Date+Extension.swift
- FiveGuyes/FiveGuyes/Sources/Models/ReadingScheduleCalculator.swift
- FiveGuyes/FiveGuyes/Sources/Models/UserBook.swift
- FiveGuyes/FiveGuyes/Sources/Views/Components/WeeklyPageCalendarView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Components/WeeklyReadingProgressView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookProgress/DailyProgressView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/Main/MainHomeView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/TotalCalendarView.swift
- 하루의 시작과 끝을 04시로 변경하여 로직 일관성을 확보합니다.
- 04시 기준으로 오늘 할당량 입력 가능 여부를 처리합니다.
- UI 텍스트 및 상태가 04시 기준으로 동적으로 변경되도록 구현합니다.
- 중복된 Date 타입 처리를 확장 메서드로 분리해 재사용성을 개선합니다.
-
> [#90] 하루의 시작과 끝을 04시로 변경

- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
- 프로젝트 타겟 버전을 기존 1.1.1에서 1.2.0으로 업데이트하였습니다.
- 앱 스토어 배포 준비를 위해 버전 업그레이드 진행.
-
> [#100] 타겟 버전 1.2.0로 업데이트

- FiveGuyes/FiveGuyes/Info.plist
- info.plist에 수출 규정 과련 프로퍼티를 추가해줍니다.
- 
-
> [#102] 수출 규정 관련 프로퍼티 추가

- FiveGuyes/FiveGuyes/Resources/Extensions/Calendar+Extension.swift
- FiveGuyes/FiveGuyes/Sources/Models/UserBook/UserBookModelV2/ReadingProgress.swift
- FiveGuyes/FiveGuyes/Sources/Views/Components/WeeklyPageCalendarView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Components/WeeklyReadingProgressView.swift
- 메인 홈의 위클리 뷰를 수정합니다.
- 뷰 수정 (페이징 스크롤 뷰, 마지막 독서일 이미지 추가)
> [#111] 메인 홈 위클리 뷰 업데이트

- FiveGuyes/FiveGuyes/Resources/Extensions/Calendar+Extension.swift
- FiveGuyes/FiveGuyes/Resources/Extensions/Date+Extension.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookSetting/CompletionCalendarView.swift
- 날짜 선택 시 총 읽기 기간(일수) 표시
- 선택한 날짜에 따른 하루 읽기 페이지 계산 및 표시 기능 추가
- 날짜 선택 화면 UI 개선
> [#117] 날짜 선택 시 읽기 기간 및 하루 페이지 계산 기능 추가

- FiveGuyes/FiveGuyes/Sources/Models/NotificationType.swift
> [#121] 노티 제목 업데이트

- FiveGuyes/FiveGuyes/Sources/Models/ReadingScheduleCalculator.swift
- FiveGuyes/FiveGuyes/Sources/Views/Components/CompletionListView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookCompletion/CompletionCelebrationView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookSetting/BookSettingsManagerView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookSetting/CompletionCalendarView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/Main/MainHomeView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Shared/CustomBackButton.swift
- 책 등록 과정에서 바뀐 뷰를 수정합니다.
- 완독 리스트에서 삭제 기능을 추가합니다.
> [#130] 책 등록 텍스트 뷰 수정 & 완독 리스트 삭제 기능 추가

- FiveGuyes/FiveGuyes/Sources/Stores/NavigationCoordinator.swift
- FiveGuyes/FiveGuyes/Sources/Views/Components/CompletionListView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookCompletion/CompletionReviewView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/Main/MainHomeView.swift
- 이미 완독한 책들의 리뷰를 수정하는 기능을 추가합니다.
<br/>
> [#132] 완독 리뷰 수정 기능 추가

- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
- FiveGuyes/FiveGuyes/Sources/Stores/BookSettingInputModel.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookSetting/BookPageSettingView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookSetting/BookSearch/BookSearchView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookSetting/BookSettingsManagerView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookSetting/CompletionCalendarView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookSetting/FinishGoalView.swift
- 책 페이지를 입력받는 텍스트 필드의 인풋 타입을 Int로 변경
- 빠른 업데이트를 위해 프로젝트 버전 1.3.3 변경
> [#140] 책 페이지를 입력 받는 텍스트 필드 인풋 타입 변경

- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
- FiveGuyes/FiveGuyes/Sources/Stores/BookSettingInputModel.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookSetting/BookPageSettingView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookSetting/BookSearch/BookSearchView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookSetting/BookSettingsManagerView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookSetting/CompletionCalendarView.swift
- FiveGuyes/FiveGuyes/Sources/Views/Screen/BookSetting/FinishGoalView.swift
> Update Version 1.3.3

- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
- 업데이트할 때, Crashlytics에 dSYM 파일을 자동 업로드하기 위한 스크립트를 추가합니다.
> [#142] dSYM 파일 자동 업로드 기능 추가

- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
> [#146] version 1.3.4 변경

- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
> [#157] Version 1.4.0

- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
- hotfix 문제를 해결하고 업데이트를 진행합니다.
- 프로젝트 버전을 1.4.1로 변경합니다.
> [#161] version 1.4.1 업데이트

- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
> [#164] Update project version to 1.5.0

- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
> [#182] 프로젝트 버전 1.5.3 업데이트

- FiveGuyes/FiveGuyes.xcodeproj/project.pbxproj
- FiveGuyes/FiveGuyes/Sources/Presentation/View/Main/MainHomeView.swift
- merge 과정에서 발생한 차이를 최종 프로퍼티 기준으로 정리 (mainHomeView, totalCalendar)
- project.pbxproj 최신화 (새로운 파일 경로 반영 및 충돌 해결)
- MARKETING_VERSION 1.5.3 → 1.5.4 업데이트
> [#190] 프로젝트 업데이트 및 버전 관리
